# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b31f4df97419761b1d8d1e6b47b943bb5bdb89d44f951e7738982d326ccf0d6a964e4391d35ecd5c8c698192edd1a7bcf8f31f180fb73c7c2e23e5d8cee79d82

test:
  secret_key_base: 0435ee3b3881a2280f4fb44716e3a190208b2a5482ba8ce11ab8d0447b6bb7f8b94b370c6f1ff2bb42dadc95fb8a227b9103f7181791f53acee13d79d50af8cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
